[1]
label = maintie_g_2_eval
model_type = spert
model_path = bert-base-cased
tokenizer_path = bert-base-cased
dataset_path = D:/Repos/nlp_tlp/maintie/models/data/g-2/maintie_test.json
types_path = /home/291928k/uwa/alcoa/root-cause-analysis-paper/maintie/models/data/g-2/maintie_types.json
eval_batch_size = 1
rel_filter_threshold = 0.4
size_embedding = 25
prop_drop = 0.1
max_span_size = 10
store_predictions = true
store_examples = true
sampling_processes = 4
max_pairs = 1000
log_path = data/log/
train_path = /home/291928k/uwa/alcoa/root-cause-analysis-paper/maintie/models/data/g-2/maintie_train.json
valid_path = /home/291928k/uwa/alcoa/root-cause-analysis-paper/maintie/models/data/g-2/maintie_dev.json
save_path = data/save/

